### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by jshnaidman** [closedcube/ClosedCube_HDC1080_Arduino#5]
I wrote my own library but I'm getting 125.0C 0% humidity regardless of anything, which is the same result as when I use this library.

I'm wondering if my sensor is broken. Does this library actually work or was this a failed attempt?

**Comment by TorbanP** [comment]
No issues here.. i used the library for testing but had to make my own in the end due to a more complicated configuration.

The HTC1080s are pretty tough, ive reworked a few of them.

I also picked up a few of the closedcube BBB a while back. Plugged one in to an Uno just now and it works fine (example sketch HDC1080measurement)

Uno -> HDC1080
Gnd->Gnd
5v-> VDD
A4 -> SDA (Data)
A5-> SCL (Clock)

i also use mine with 3.3v logic and have no issues.
![photo_2017-07-30_14-18-19](https://user-images.githubusercontent.com/8907765/28756764-0098e0c8-7532-11e7-8d4f-b27d810063b4.jpg)

**Comment by closedcube** [comment]
@TorbanP - Many thanks for the quick demo and cehck

**Comment by jshnaidman** [comment]
Thanks m8. I believe I broke my sensor by soldering with temperatures above the peak temperature listed on the data sheet.
